### ISSUE TITLE
Unable to craft Iron Wand

### ISSUE THREAD

**Issue by Cupears** [Appocryptha/Liminal-Industries#197]
A clear and concise description of what the bug is:
Just a crafting conflict with the iron wand and the spatula, cant make the iron wand.

Craft iron wand -> Gets Spatula :)

A clear and concise description of what you expected to happen:
Conflicting Crafting with Iron wand. Makes Spatula instead.

~~I Recommending getting [Polymorph Mod](https://www.curseforge.com/minecraft/mc-mods/polymorph)~~

If applicable, add screenshots to help explain your problem:
<img width="997" height="819" alt="Image" src="https://github.com/user-attachments/assets/c48e0473-6d06-494b-b2c9-15ffd7bfdfa3" />

**Comment by morpheus3141** [comment]
I noticed that too, if you use treated sticks it works and does not make a spatula. Still, JEI recipe should be fixed.

**Comment by Aceplante** [comment]
Either change the recipe or add polymorph

**Comment by Aceplante** [comment]
It seems to be already fixed. Not sure if that fix was made since this was reported

**Comment by Render-Err** [comment]
I still have the same issue in latest ver.
I suggest changing the spatula recipe to use an iron plate instead,
